name: Pruebas unitarias
on:
  push:
    branches: [recetario]

jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuraci√≥n de entorno de python
      uses: actions/setup-python@v2
      run: pip install -r requirements.txt
      with:
        python-version: '3.7'
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest -v tests/test_persona.py
    - name: Calculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest tests/test_persona.py
          coverage report -m
